workflows:
  ios-release:
    name: iOS Production Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Build Release IPA
        script: |
          flutter clean
          flutter pub get
          cd ios && pod install && cd ..
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa  # Ensure this matches the actual build output
    publishing:
      app_store_connect:
        api_key_id: "Innomatrics Technologies"  
        issuer_id: "29f996f7-d320-4397-957d-b9fba3713fff"    
        api_key: "HU24V233MP"
        ipa_path: build/ios/ipa/*.ipa 
        notify: false
