// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhBLX4RrIl2nRM3SIWAx_8nbMosuDqmDc',
    appId: '1:121392168783:web:d4fc748467fa3ca4144f3a',
    messagingSenderId: '121392168783',
    projectId: 'bus-booking-application-aa7e5',
    authDomain: 'bus-booking-application-aa7e5.firebaseapp.com',
    storageBucket: 'bus-booking-application-aa7e5.appspot.com',
    measurementId: 'G-QYW2G8MNBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEqKsO7dBuqypkujoh5TdeO-Kgw3ZTBsI',
    appId: '1:121392168783:android:e90dad79d2a6f309144f3a',
    messagingSenderId: '121392168783',
    projectId: 'bus-booking-application-aa7e5',
    storageBucket: 'bus-booking-application-aa7e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2wqWPEEn2vUKhoa-EpflKcTq5q6edrWk',
    appId: '1:121392168783:ios:e814bd9ee8efea8b144f3a',
    messagingSenderId: '121392168783',
    projectId: 'bus-booking-application-aa7e5',
    storageBucket: 'bus-booking-application-aa7e5.appspot.com',
    iosBundleId: 'com.example.busBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2wqWPEEn2vUKhoa-EpflKcTq5q6edrWk',
    appId: '1:121392168783:ios:e814bd9ee8efea8b144f3a',
    messagingSenderId: '121392168783',
    projectId: 'bus-booking-application-aa7e5',
    storageBucket: 'bus-booking-application-aa7e5.appspot.com',
    iosBundleId: 'com.example.busBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhBLX4RrIl2nRM3SIWAx_8nbMosuDqmDc',
    appId: '1:121392168783:web:799e27981065ae36144f3a',
    messagingSenderId: '121392168783',
    projectId: 'bus-booking-application-aa7e5',
    authDomain: 'bus-booking-application-aa7e5.firebaseapp.com',
    storageBucket: 'bus-booking-application-aa7e5.appspot.com',
    measurementId: 'G-PP7GJYKYR8',
  );
}
